name: Package
on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@main

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Test install
      run: |
        pip install .[test]

    - name: Test with pytest
      run: pytest

    - name: Build
      run: python setup.py sdist

    - name: Publish the wheel to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: dist/
        skip-existing: true
